// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByxU8ZmsVeio9Yv0dhLgrxYsS_wRELsAg',
    appId: '1:920872350623:web:b9111e81330ef6a9f9c3aa',
    messagingSenderId: '920872350623',
    projectId: 'mirxtremapps-48409',
    authDomain: 'mirxtremapps-48409.firebaseapp.com',
    storageBucket: 'mirxtremapps-48409.appspot.com',
    measurementId: 'G-K29WKZZJW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnO1csIkv4WAOB2mY2BZqRZeilnghvD3A',
    appId: '1:920872350623:android:35ce555bd2fb42e8f9c3aa',
    messagingSenderId: '920872350623',
    projectId: 'mirxtremapps-48409',
    storageBucket: 'mirxtremapps-48409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ZZnb4mF-80G0k008t77tjVKsx8R5_9w',
    appId: '1:920872350623:ios:f8f54947f165bf7ff9c3aa',
    messagingSenderId: '920872350623',
    projectId: 'mirxtremapps-48409',
    storageBucket: 'mirxtremapps-48409.appspot.com',
    iosBundleId: 'com.mirxtremapps.flutterTdd',
  );
}
